"""mkdocs on_pre_build hook (R6 B7): generate print-ready pages.

Produces:
  docs/print/checklists.md  — every chapter's `## Checkpoint` list, one per
                               printed page (page-break before each), for
                               docs/stylesheets/print.css to render cleanly.
  docs/print/bin-labels.md  — one label per assembly chapter plus "Spares"
                               and "Klicky (bagged)": chapter number, title,
                               its Printed-parts group names, and a QR code
                               (generated with segno, SVG, no external
                               service) linking to the live chapter URL.

Both files are regenerated on every build — never hand-edit them. QR SVGs
are written to docs/print/assets/qr/.
"""

import re
from pathlib import Path

try:
    import segno
except ImportError:  # pragma: no cover - degrade gracefully if not installed
    segno = None

REPO = Path(__file__).resolve().parent.parent
DOCS = REPO / "docs"
MANUAL = DOCS / "manual"
PRINT_DIR = DOCS / "print"
QR_DIR = PRINT_DIR / "assets" / "qr"

_SITE_URL = "https://alexlicohen.github.io/voron-24-350-build-manual/"

_EXCLUDE = {"00-index.md", "00-tonight.md", "CONVENTIONS.md"}
_CHAPTER_TITLE_RE = re.compile(r"^#\s*Chapter\s+(\d+)\s*—\s*(.+?)\s*$", re.MULTILINE)
_CHECKPOINT_RE = re.compile(
    r"^##\s*Checkpoint\s*\S*\s*$\n(.*?)(?=^##\s|\Z)", re.MULTILINE | re.DOTALL
)
_PRINTED_PARTS_RE = re.compile(
    r"^\*\*Printed parts\*\*\s*\n\n(.*?)(?=\n\n)", re.MULTILINE | re.DOTALL
)
_STL_CELL_RE = re.compile(r"`([\w\[\]-]+\.stl)`")
_TABLE_ROW_RE = re.compile(r"^\s*\|(.+)\|\s*$", re.MULTILINE)


def _chapter_files():
    return sorted(f for f in MANUAL.glob("*.md") if f.name not in _EXCLUDE)


def _slug_for(path):
    return path.stem


def _chapter_url(path):
    # mkdocs `use_directory_urls` default (true): NN-slug.md -> manual/NN-slug/
    return f"{_SITE_URL}manual/{_slug_for(path)}/"


def _parse_header(text):
    m = _CHAPTER_TITLE_RE.search(text)
    if not m:
        return None, None
    return m.group(1), m.group(2)


def _checkpoint_items(text):
    m = _CHECKPOINT_RE.search(text)
    if not m:
        return []
    items = []
    for line in m.group(1).splitlines():
        line = line.strip()
        if line.startswith("- [ ]") or line.startswith("- [x]"):
            items.append(line[5:].strip())
    return items


def _printed_part_names(text):
    m = _PRINTED_PARTS_RE.search(text)
    if not m:
        return []
    names = []
    for row in _TABLE_ROW_RE.finditer(m.group(1)):
        for stl in _STL_CELL_RE.findall(row.group(1)):
            names.append(stl)
    return names


def _write_qr(slug, url):
    if segno is None:
        return None
    QR_DIR.mkdir(parents=True, exist_ok=True)
    out = QR_DIR / f"{slug}.svg"
    segno.make(url, error="m").save(out, kind="svg", scale=4, border=2)
    return out.relative_to(PRINT_DIR)


def build_checklists_markdown(chapters):
    lines = [
        "# Printable checklists",
        "",
        "_Generated by `scripts/build_printables.py` — do not hand-edit. Print with "
        "`.print-images` off (default) for a text-only sheet._",
        "",
    ]
    first = True
    for path, number, title, text in chapters:
        items = _checkpoint_items(text)
        if not items:
            continue
        if not first:
            lines.append('<div class="print-page-break"></div>')
            lines.append("")
        first = False
        lines.append(f"## Chapter {number} — {title}")
        lines.append("")
        for item in items:
            lines.append(f"- [ ] {item}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _label_block(title, subtitle, part_names, qr_rel):
    lines = [f"### {title}", ""]
    if subtitle:
        lines.append(f"_{subtitle}_")
        lines.append("")
    if part_names:
        lines.append("**Printed parts:**")
        for n in part_names:
            lines.append(f"- `{n}`")
    else:
        lines.append("_(no printed parts logged)_")
    lines.append("")
    if qr_rel:
        lines.append(f"![QR link to live chapter]({qr_rel})")
    lines.append("")
    return lines


def build_bin_labels_markdown(chapters):
    lines = [
        "# Bin labels",
        "",
        "_Generated by `scripts/build_printables.py` — do not hand-edit. Cut along the "
        "label boundaries; each QR links to the live chapter page._",
        "",
    ]

    for path, number, title, text in chapters:
        part_names = _printed_part_names(text)
        qr_rel = _write_qr(_slug_for(path), _chapter_url(path))
        lines += _label_block(f"Chapter {number} — {title}", None, part_names, qr_rel)
        lines.append('<div class="print-page-break"></div>')
        lines.append("")

    lines += _label_block(
        "Spares", "Extra fasteners / printed-part overages held back from every batch", [], None
    )
    lines.append('<div class="print-page-break"></div>')
    lines.append("")
    lines += _label_block(
        "Klicky (bagged)",
        "Reserved for the deferred Klicky probe mod — see docs/manual/98-mods.md when it exists",
        [],
        None,
    )

    return "\n".join(lines).rstrip() + "\n"


def _load_chapters():
    chapters = []
    for path in _chapter_files():
        text = path.read_text(encoding="utf-8")
        number, title = _parse_header(text)
        if number is None:
            continue
        chapters.append((path, number, title, text))
    return chapters


def on_pre_build(config, **kwargs):
    PRINT_DIR.mkdir(parents=True, exist_ok=True)
    chapters = _load_chapters()
    (PRINT_DIR / "checklists.md").write_text(
        build_checklists_markdown(chapters), encoding="utf-8"
    )
    (PRINT_DIR / "bin-labels.md").write_text(
        build_bin_labels_markdown(chapters), encoding="utf-8"
    )


if __name__ == "__main__":
    chapters = _load_chapters()
    print(build_checklists_markdown(chapters)[:2000])
    print("---")
    print(build_bin_labels_markdown(chapters)[:2000])
