"""mkdocs on_pre_build hook (R6 C4): generate docs/manual/00-tonight.md.

Parses every assembly chapter (docs/manual/NN-*.md, in filename/timeline
order) for the `**Time:**`, `**Sessions:**` and `Pause: ~NN min since the
last pause — <state>` lines and emits a single generated page:

  - a top summary of total remaining hours (from each chapter's Time range)
  - a 30/60/90-minute planner built by greedily packing pause-delimited
    segments in timeline order
  - a per-chapter list of segments "Step X.Y -> Step X.Z - ~NN min -
    leave-state: <state>", each carrying `data-first-step` so progress.js can
    grey out segments whose first step is already marked done in
    localStorage.

If a chapter has no Pause lines yet (chapters are being written
concurrently), it gets a single "no stopping points marked yet" row instead
of being skipped.

This file is regenerated on every build — never hand-edit
docs/manual/00-tonight.md.
"""

import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MANUAL = REPO / "docs" / "manual"
OUT = MANUAL / "00-tonight.md"

_CHAPTER_TITLE_RE = re.compile(r"^#\s*Chapter\s+(\d+)\s*—\s*(.+?)\s*$", re.MULTILINE)
_TIME_RE = re.compile(r"^\*\*Time:\*\*\s*(.+)$", re.MULTILINE)
_TIME_RANGE_RE = re.compile(r"(\d+(?:\.\d+)?)\s*(?:[–-]\s*(\d+(?:\.\d+)?))?\s*h")
_STEP_HEADING_RE = re.compile(r"^###\s*Step\s+([A-Za-z]?\d+[A-Za-z]?\.\d+)\b.*$", re.MULTILINE)
_PAUSE_RE = re.compile(
    r"^>?\s*Pause:\s*~?(\d+)\s*min\s*since the last pause\s*—\s*(.+?)\s*$",
    re.MULTILINE,
)
_EXCLUDE = {"00-index.md", "00-tonight.md", "CONVENTIONS.md"}


def _chapter_files():
    files = sorted(
        f for f in MANUAL.glob("*.md")
        if f.name not in _EXCLUDE
    )
    return files


def _midpoint_hours(time_line):
    m = _TIME_RANGE_RE.search(time_line or "")
    if not m:
        return None
    lo = float(m.group(1))
    hi = float(m.group(2)) if m.group(2) else lo
    return (lo + hi) / 2.0


def _parse_chapter(path):
    text = path.read_text(encoding="utf-8")
    title_m = _CHAPTER_TITLE_RE.search(text)
    number = title_m.group(1) if title_m else path.stem
    title = title_m.group(2) if title_m else path.stem
    time_m = _TIME_RE.search(text)
    hours = _midpoint_hours(time_m.group(1)) if time_m else None

    steps = list(_STEP_HEADING_RE.finditer(text))
    if not steps:
        return {
            "number": number, "title": title, "path": path, "hours": hours,
            "segments": [],
        }

    step_positions = [(m.start(), m.group(1)) for m in steps]

    segments = []
    seg_start_id = step_positions[0][1]
    seg_start_pos = step_positions[0][0]
    for pm in _PAUSE_RE.finditer(text):
        minutes, leave_state = int(pm.group(1)), pm.group(2)
        pause_pos = pm.start()
        # last step heading at or before this pause
        last_step = None
        for pos, sid in step_positions:
            if pos <= pause_pos:
                last_step = sid
            else:
                break
        if last_step is None:
            continue
        segments.append({
            "first_step": seg_start_id,
            "last_step": last_step,
            "minutes": minutes,
            "leave_state": leave_state,
        })
        # next segment starts at the first step heading after this pause
        next_start = None
        for pos, sid in step_positions:
            if pos > pause_pos:
                next_start = sid
                break
        if next_start is None:
            break
        seg_start_id = next_start

    return {
        "number": number, "title": title, "path": path, "hours": hours,
        "segments": segments,
    }


def _plan_for_budget(flat_segments, budget):
    picked, total = [], 0
    for seg in flat_segments:
        if not picked or total + seg["minutes"] <= budget:
            picked.append(seg)
            total += seg["minutes"]
        else:
            break
    return picked, total


def _segment_line(seg):
    label = f"Step {seg['first_step']} → Step {seg['last_step']}"
    return (
        f'- <span data-first-step="{seg["first_step"]}">{label} · '
        f'~{seg["minutes"]} min · leave-state: {seg["leave_state"]}</span>'
    )


def build_tonight_markdown():
    chapters = [_parse_chapter(f) for f in _chapter_files()]

    total_hours = sum(c["hours"] for c in chapters if c["hours"] is not None)

    flat_segments = []
    for c in chapters:
        for seg in c["segments"]:
            flat_segments.append(dict(seg, chapter=f"Ch {c['number']}"))

    lines = [
        "# Tonight",
        "",
        "_Generated by `scripts/build_tonight.py` on every build — do not hand-edit. "
        "Checked-off state is overlaid client-side from your browser's saved progress._",
        "",
        f"**Total remaining (estimate):** ~{total_hours:.1f} h hands-on across "
        f"{len(chapters)} chapters.",
        "",
        "## Tonight's planner",
        "",
    ]

    if not flat_segments:
        lines.append(
            "_No stopping points marked yet anywhere in the manual — chapters are still "
            "being written. Check back once `Pause:` lines land._"
        )
    else:
        for label, budget in (("30 min", 30), ("60 min", 60), ("90 min", 90)):
            picked, total = _plan_for_budget(flat_segments, budget)
            lines.append(f"**If you have {label}:**")
            for seg in picked:
                lines.append(f"- {seg['chapter']} — {_segment_line(seg)[2:]}")
            lines.append("")

    lines += ["", "---", "", "## By chapter (timeline order)", ""]

    for c in chapters:
        lines.append(f"### Chapter {c['number']} — {c['title']}")
        if not c["segments"]:
            lines.append("- no stopping points marked yet")
        else:
            for seg in c["segments"]:
                lines.append(_segment_line(seg))
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def on_pre_build(config, **kwargs):
    OUT.write_text(build_tonight_markdown(), encoding="utf-8")


if __name__ == "__main__":
    print(build_tonight_markdown())
